### ISSUE TITLE
package installation error

### ISSUE THREAD

**Issue by bajrang8955** [robincsamuel/laravel-msg91#1]
when I run composer update, this problem occurs.
The requested package robincsamuel/laravel-msg91 ~1 exists as robincsamuel/laravel-msg91[dev-master] but these are rejected by your constraint.

**Comment by robincsamuel** [comment]
@bajrang8955 Can you copy your composer.json here?I think you are using the wrong version. please use dev-master.

**Comment by robincsamuel** [comment]
I noticed the wrong version in the readme. please use,

```
"require": {
    "robincsamuel/laravel-msg91": "dev-master"
}
```
