### ISSUE TITLE
RobinCSamuel\LaravelMsg91 not working on live website

### ISSUE THREAD

**Issue by vineet253** [robincsamuel/laravel-msg91#10]
I am using RobinCSamuel\LaravelMsg91 with sending transitional msg code working in local but same code push on the live  server and msg not send.

**Comment by robincsamuel** [comment]
@vineet253 Are you getting any error?

**Comment by vineet253** [comment]
No Sir I haven't displayed any error.

**Comment by vineet253** [comment]
[message] => Authentication failure
    [type] => error

**Comment by robincsamuel** [comment]
Are you sure the credentials are correct? Since it's working fine on local, and you're getting an authentication error on live server, I suspect the credentials are wrong.

**Comment by robincsamuel** [comment]
I'm closing this issue since no response. Please reopen the issue in case you're stuck.
