### ISSUE TITLE
resendOtp api

### ISSUE THREAD

**Issue by pintu24aipl** [robincsamuel/laravel-msg91#11]
rensendOtp is not working. After analyse some time I found that  when I use sendOtp then it send otp to number but when I hit on resendOtp no otp is recieved. and resendOtp api omit the country code from a number.
for example +919814253678 becomes 9814253678 in resend otp

**Comment by robincsamuel** [comment]
@pintu24aipl Can you try `919814253678` instead of `+919814253678` (Without `+`) as mentioned in the documentation?

**Comment by robincsamuel** [comment]
I'm closing this issue, please feel free to reopen if you are still facing the same.
