### ISSUE TITLE
Wrong SenderId in my SMS

### ISSUE THREAD

**Issue by abhiburk** [robincsamuel/laravel-msg91#14]
Hi,
I have set sender id as ATRATR but its still going as QP-SNDOTP. This issue is coming since last few days. Kindly check this

**Comment by robincsamuel** [comment]
Are you sure it's not an issue with msg91?

**Comment by Mohd-Uzair** [comment]
new to laravel how to use it futher ??

**Comment by robincsamuel** [comment]
@Mohd-Uzair Please check the documentation, there are step by step instructions.
