### ISSUE TITLE
DLT Template

### ISSUE THREAD

**Issue by smarteertech** [robincsamuel/laravel-msg91#22]
Please add one more URL params called DLT_TE_ID to pass on to the API. It is mandatory now.

**Comment by robincsamuel** [comment]
@smarteertech Can you elaborate a bit more? Is it when you sending an sms or for the sendOtp function?

**Comment by smarteertech** [comment]
Someone already added it seems, you can refer this forked version for the exact change.
https://github.com/Hironate/laravel-msg91/commit/06e87ee2b233adfb02d9f009280bb1a753626374

**Comment by robincsamuel** [comment]
I see that, but I'm not sure that'll solve all the cases. For example, there is a `sendOtp` function, the above-mentioned change is only for the `message` function. I'm trying to find more about this param and maybe implement that to work for all the cases and also include examples.

**Comment by smarteertech** [comment]
Sure, for now, we added this params and used for our message, it works good. I am not sure about OTP.

**Comment by robincsamuel** [comment]
Can you show me an example working request? I can cross-check and merge that PR.

**Comment by smarteertech** [comment]
We are sending DLT template like this
`$sms = LaravelMsg91::message($journey->customer_phone, $message, array('DLT_TE_ID' => '1234567890123546798'));`

**Comment by robincsamuel** [comment]
Thanks for sharing the details, I'm merging the PR.
