### ISSUE TITLE
Non-static method RobinCSamuel\LaravelMsg91\LaravelMsg91::message() should not be called statically

### ISSUE THREAD

**Issue by iqbal619** [robincsamuel/laravel-msg91#3]
Hello robincsamuel,
After installing robincsamuel/laravel-msg91 via composer, i am trying to send message but am getting this non-static method error. what i have to do?

**Comment by robincsamuel** [comment]
@iqbal619 Could you paste your code here please ?

**Comment by pnbhanderi32** [comment]
LaravelMsg91::sendOtp($mobile, $otp, "Your otp for verification is ".$otp);

> Non-static method RobinCSamuel\\LaravelMsg91\\LaravelMsg91::sendOtp() should not be called statically
