### ISSUE TITLE
$msgtype errror

### ISSUE THREAD

**Issue by jigs1212** [robincsamuel/laravel-msg91#5]
$result = LaravelMsg91::verifyOtp(919090909090, 1290); // returns true or false
while using the above method receiving stdClass error.

$result = LaravelMsg91::verifyOtp(919090909090, 1290, ['raw' => true]); // returns what msg91 replies (includes error message & type)
i found that using the above the object received doesnot have $msgType and only has {message: '', type:'success'}

please update the following line
return json_decode($response->getBody())->msgType == 'success' ? true : false;
to 
return json_decode($response->getBody())->type == 'success' ? true : false;

**Comment by robincsamuel** [comment]
@jigs1212 I think `msg91` recently changed this, it was `msgType`. I'll check and update. Or if you have changed it and verified already, a PR is appreciated :)

**Comment by robincsamuel** [comment]
Nevermind, I've checked the docs & updated, Thanks! :)
