### ISSUE TITLE
Unable to send SMS on server, Works fine at local.

### ISSUE THREAD

**Issue by shahbaz17** [robincsamuel/laravel-msg91#6]
Hi Robin,

Is this repo still valid for v5.7?

Because I tried sending SMS on the server, there shows error.

Could you help?

**Comment by jigs1212** [comment]
whats the error?
share some details of server and local

**Comment by robincsamuel** [comment]
@shahbaz17 It should work. can you please share the error details?

**Comment by shahbaz17** [comment]
Tried all again, this time showing this
`"Class 'App\Http\Controllers\LaravelMsg91' not found"`

**Comment by shahbaz17** [comment]
Oh sorry,
Didn't use this
`use RobinCSamuel\LaravelMsg91\Facades\LaravelMsg91;`

Now it's returning 
`{#250 ▼
  +"message": "Authentication failure"
  +"type": "error"
}
`

**Comment by shahbaz17** [comment]
I got it working for local system.

changed the config file from **config/msg91.php** to **config/laravel-msg91.php** because in message function there is config('laravel-msg91.auth_key');

**Comment by jigs1212** [comment]
> I got it working for local system.
> 
> changed the config file from **config/msg91.php** to **config/laravel-msg91.php** because in message function there is config('laravel-msg91.auth_key');

I dont think thats require.
